name: Test SDK

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./sdk

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: sdk/package-lock.json
    - name: Install dependencies.
      run: npm ci
    - name: Build NPM package.
      run: npm run build --if-present
    - name: Run testsuits.
      run: npm test
